language: python
python:
- '3.5'
env:
  global:
  - PROJECT_ID=moves-gae
  - STORAGE_BUCKET=moves-gae.appspot.com
  - IMAGE_STORE=testing/images
  - VIDEO_STORE=testing/videos
before_install:
- openssl aes-256-cbc -K $encrypted_6bd76235a7d2_key -iv $encrypted_6bd76235a7d2_iv
  -in travis-client-secret.json.enc -out travis-client-secret.json -d
install:
- pip install -r requirements.txt
script: py.test
deploy:
- provider: gae
  keyfile: travis-client-secret.json
  project: moves-gae
  on: master
- provider: gae
  keyfile: travis-client-secret.json
  project: moves-gae
  config: transcoder_worker/worker.yaml
  on: master
- provider: gae
  keyfile: travis-client-secret.json
  project: moves-gae
  version: develop
  on: develop
  no_promote: true
  no_stop_previous_version: true
