service: default
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  PROJECT_ID: moves-gae
  IMAGE_STORE: moves-gae.appspot.com/images