service: default
runtime: python
env: flex
entrypoint: gunicorn -k gevent -b :$PORT main:app

runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

env_variables:
  PROJECT_ID: moves-gae
  STORAGE_BUCKET: moves-gae.appspot.com
  IMAGE_PREFIX: images
  VIDEO_PREFIX: videos
  TRANSCODING_PREFIX: transcoding
  TRANSCODE_TOPIC: transcode_request
  SENTRY_DSN: https://d788d6b7989a410cb575e9e0f806914d:d6c0eca4ba4f4d799ce85d1dbb30b3eb@sentry.io/200794